language: ruby
cache: bundler
rvm:
  - 2.2
before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - cp config/ldap.yml.travis config/ldap.yml
env:
  global:
    - CODECLIMATE_REPO_TOKEN=a01e4f1dd1cb1fcd1cbc0cc7864c3da556b88f11f8799d4273e363b5209df084 bundle exec rake
addons:
    code_climate:
        repo_token: a01e4f1dd1cb1fcd1cbc0cc7864c3da556b88f11f8799d4273e363b5209df084
